### ISSUE TITLE
DRb::DRbRemoteError: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by x1wins** [x1wins/rails-new-with-docker-compose#2]
```
rails-new-with-docker-compose % docker-compose run --no-deps web rails test test/controllers/home_controller_test.rb     
Creating rails-new-with-docker-compose_web_run ... done
Running via Spring preloader in process 15
Run options: --seed 27476

# Running:

E

Error:
HomeControllerTest#test_should_get_index:
DRb::DRbRemoteError: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "addresses_pkey"
DETAIL:  Key (id)=(980190962) already exists.
 (ActiveRecord::RecordNotUnique)
    /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `exec'
    /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `block (2 levels) in execute'
    /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'

```

**Comment by x1wins** [comment]
Solution
- Deleted /fixtures
https://stackoverflow.com/a/39578685/1399891
